Steady camera detector using POC
morzh/repFit pull request #1
Opened 2024-06-20 00:48 UTC by morzh

2024-06-20 19:34 UTC, Ma4eteS requested changes

2024-06-20 19:34 UTC, Ma4eteS commented on cv_utils/video_frames_batch.py
> +            batch[index] = frame
работать с тем же массивом не безопасно, так как он может быть изменён в другом потоке и данные будут не верные

2024-06-20 19:34 UTC, Ma4eteS commented on cv_utils/video_frames_batch.py
> +        yield batch[:last_batch_frames_number]
Выполнение основного цикла чтения заканчивается когда кончатся кадры в видео. Не совмем понимаю назначение этого кода с 29 по 31 строку. 
Корректный результат будет если заменить его на 
if index:
     return batch[:index]

2024-06-20 19:34 UTC, Ma4eteS commented on cv_utils/video_reader.py
> +            self._progress.update()
self._progress не определён если self.use_tqdm = False

2024-06-20 19:34 UTC, Ma4eteS commented on cv_utils/video_segments_writer.py
> +import copy
чтобы не парится с сортировкой импорта, можно использовать утилиту isort.
в терминале пишешь 
isort ./cv_utils/video_segments_writer.py 
и оно сделает сортировку импортов по феншую

2024-06-20 19:34 UTC, Ma4eteS commented on cv_utils/video_segments_writer.py
> +        r"""
что делает "r" ?

2024-06-20 19:34 UTC, Ma4eteS commented on cv_utils/video_segments_writer.py
> +            Video segments inversion. Method calculates minus in sense of set theory  :math:`[0, N_{frames} - 1]  \ \backslash  \ segments`.
Description точно верный? часть с  "\ \backslash  \ segments" не понятна

2024-06-20 19:34 UTC, Ma4eteS commented on cv_utils/video_segments_writer.py
> +        segments = video_segments.segments.flatten()
Для нашего кода точно пойдёт. Но не оптимально. В этой функции создаётся до 6 массивов. 
flatten, insert, append, reshape, delete - все функции создают новый массив. Такие операции быстрей делать в python list. Но ускорение заметно с приличных размеров таблиц.

2024-06-20 19:34 UTC, Ma4eteS commented on cv_utils/video_segments_writer.py
> +        video_segments_gaps = copy.copy(video_segments)
Копирование массивов или объектов редко оправдано. Если полный набор данных далее не используется, то оптимальней вернуть новое значение отдельно (return segments) или создать структуру данных в которой передавать всю пачку значений (ссылок на массивы). Так как  video_segments уже data class, идеальный вариант - добавить в него поле gaps

2024-06-20 19:34 UTC, Ma4eteS commented on cv_utils/video_segments_writer.py
> +            if index_frame == current_segment[0]:
передача индекса внутри массива плохо читается. Вынос индексов в переменные start_idx, stop_idx  добавит читаемости

2024-06-20 19:34 UTC, Ma4eteS commented on cv_utils/video_segments_writer.py
> +        filename_frames_range = '_' + str(segment[0]) + '-' + str(segment[1]) + '__'
к примеру тут, если бы segment был структурой данных, строка выглядела бы читабельней с
filename_frames_range = '_' + str(segment.start) + '-' + str(segment.stop) + '__'

2024-06-20 19:34 UTC, Ma4eteS commented on datasets/pre_processing/cut_steady_camera_video_segments.py
> +from os.path import isfile, join, splitext
обычно используется через 
import os
эти метода есть много где и импорт их отдельно читается не очевидно

Импорт из одной либы 3-я способами - не гуд

2024-06-20 19:34 UTC, Ma4eteS commented on datasets/pre_processing/cut_steady_camera_video_segments.py
> +videos_extensions = ['.mp4', 'MP4', '.mkv', '.webm']
'MP4' без точки это ок?

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/core/image_registration/image_registration_poc.py
> +ndimageNxMx3 = Annotated[NDArray[np.uint8], Literal["N", "M", 3]]
аннотация это конечно гуд. Но от расписывания таких структур, понятней не становится, по этому на практике не используется. Ты или знаешь какой должен быть массив или тебе это не важно, так как не пользуешься этим на практике, а только читаешь код.

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/core/image_registration/image_registration_poc.py
> +        :param new_image: image to add to deque
Если написать тут 
:param new_image: image to add to deque = np.array(10, 20, 3)
это будет читаться.  
ndimageNxM в типизации совсем не читается

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/core/image_registration/image_registration_poc.py
> +        :param new_image: image to add to deque
Если эта типизация работает для проверки кода, то это ещё ок. Но если она и этого не может, то бесполезна. Так как с не правильным массивом код не отработает и подсказка за пару секунд до ошибки почти ни чего не делает

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/core/image_registration/image_registration_poc.py
> +        :param new_image: image to add to deque
я ставлю в таких случаях 
:np.ndarray
оно и читается и работает на проверку, подсвечивая когда передаётся не массив

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/core/image_registration/image_registration_poc.py
> +        :param image_reference:  reference image
такие строки не нужны. Не добавляют информативности, но читаются

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/core/ocr/craft.py
> +from cv2 import typing
выделение typing из cv2 делает его использование плохо читемым, так как typing сам по себе является стандартной либой

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/core/ocr/craft.py
> +    def draw_polygons(image_shape: tuple[int, int], polygons: list[list[list[int]]]) -> np.ndarray:
це точно перебор - list[list[list[int]]]  
 list вполне достаточно

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/core/ocr/easy_ocr.py
> +    def pixel_mask(self, image: cv2.typing.MatLike, output_resolution: tuple[int, int]) -> cv2.typing.MatLike:
cv2.typing.MatLike - вот тут отлично читается

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/core/ocr/tesseract_ocr.py
> +        d = pytesseract.image_to_data(image, output_type=pytesseract.Output.DICT)
flake запрещает именование переменных в 1 символ. 
Обычно это ок только для совсем стандартных имён типа i и (x, y, w, h) ниже

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/core/steady_camera_coarse_filter.py
> +        poc_scale_factor = float(self.poc_maximum_image_dimension) / max(self.video_frames_batch.video_reader.resolution)
совсем пофигу, но зачем конвертация в float? деление в python всегда возвращает float

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/core/steady_camera_coarse_filter.py
> +        poc_resolution = (round(original_resolution[0] * poc_scale_factor), round(original_resolution[1] * poc_scale_factor))
round стоит дорого. Не стоит его применять в больших вычислениях. Если нужно сделать целым и не важно +-0.5, int лучше

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/core/steady_camera_coarse_filter.py
> +        self.poc_resolution = int(poc_resolution[0]), int(poc_resolution[1])
а следующей строкой int )))

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/core/steady_camera_coarse_filter.py
> +        segments_bins = np.linspace(0, (number_bins - 1) * number_frames_to_average, number_bins, dtype=np.int32).reshape(-1, 1) + base_segment_range
Длина строки на практике до 120 символов

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/core/steady_camera_coarse_filter.py
> +    def unite_overlapping_ranges(segments: segments_list) -> segments_list:
_list говорит о том что оно с типом данных list. 
Для массивов лучше писать _array

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/extract_video_segmens.py
> +    match image_registration_parameters['text_mask_model']:
первый раз вижу использование оператора match\case

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/extract_video_segmens.py
> +        case _:
тут case понимает что "_" это "всё остальное" без объявления переменной "_" ?

2024-06-20 19:34 UTC, Ma4eteS commented on filters/steady_camera_filter/extract_video_segmens.py
> +    camera_filter = SteadyCameraCoarseFilter(video_filepath,
в случае передачи множества именованных параметров с совпадающими ключами, удобней добавить в функцию аргумент **kwargs и вызывать с 
  camera_filter = SteadyCameraCoarseFilter(video_filepath,  ocr_model, **image_registration_parameters)

2024-06-20 19:34 UTC, Ma4eteS commented on utils/multiprocess.py
> -def run_pool(func, args: list, n_process: int = 12):
исходный run_pool можно и оставить

2024-06-20 19:34 UTC, Ma4eteS commented on utils/multiprocess_torch.py
зачем разделять multiprocess тулсы ?

2024-06-20 20:49 UTC, morzh commented on filters/steady_camera_filter/extract_video_segmens.py
> +    match image_registration_parameters['text_mask_model']:
А я обрадовался, что старый сишный оператор пришёл и в питон ))

2024-06-20 20:53 UTC, morzh commented on cv_utils/video_segments_writer.py
> +        r"""
далает рендеринг формул

2024-06-20 20:53 UTC, morzh commented on cv_utils/video_segments_writer.py
> +        r"""
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010501280-PyCharm-Documentation-Improvements

2024-06-20 20:55 UTC, morzh commented on utils/multiprocess.py
> -def run_pool(func, args: list, n_process: int = 12):
исправил

2024-06-20 20:55 UTC, morzh commented on utils/multiprocess_torch.py
исправил

2024-06-20 20:59 UTC, morzh commented on cv_utils/video_segments_writer.py
> +            Video segments inversion. Method calculates minus in sense of set theory  :math:`[0, N_{frames} - 1]  \ \backslash  \ segments`.
![image](https://github.com/morzh/repFit/assets/5655483/392402b7-ae07-4937-a372-62137613df3f)

2024-06-20 21:00 UTC, morzh commented on cv_utils/video_segments_writer.py
> +            Video segments inversion. Method calculates minus in sense of set theory  :math:`[0, N_{frames} - 1]  \ \backslash  \ segments`.
Это разметка LaTeX'a. \backslash  -- это минус в теоретико-множественном смысле.

2024-06-20 21:01 UTC, morzh commented on datasets/pre_processing/cut_steady_camera_video_segments.py
> +videos_extensions = ['.mp4', 'MP4', '.mkv', '.webm']
исправил

2024-06-21 04:23 UTC, morzh commented on cv_utils/video_segments_writer.py
> +            Video segments inversion. Method calculates minus in sense of set theory  :math:`[0, N_{frames} - 1]  \ \backslash  \ segments`.
Description подправил

2024-06-21 04:24 UTC, morzh commented on datasets/pre_processing/cut_steady_camera_video_segments.py
> +from os.path import isfile, join, splitext
done

2024-06-21 04:27 UTC, morzh commented on filters/steady_camera_filter/core/ocr/craft.py
> +from cv2 import typing
done

2024-06-21 04:28 UTC, morzh commented on filters/steady_camera_filter/core/ocr/tesseract_ocr.py
> +        d = pytesseract.image_to_data(image, output_type=pytesseract.Output.DICT)
done

2024-06-21 04:34 UTC, morzh commented on filters/steady_camera_filter/core/steady_camera_coarse_filter.py
> +        poc_resolution = (round(original_resolution[0] * poc_scale_factor), round(original_resolution[1] * poc_scale_factor))
делается для всего видео один раз

2024-06-21 04:35 UTC, morzh commented on filters/steady_camera_filter/core/steady_camera_coarse_filter.py
> +        poc_resolution = (round(original_resolution[0] * poc_scale_factor), round(original_resolution[1] * poc_scale_factor))
исправил

2024-06-21 04:37 UTC, morzh commented on filters/steady_camera_filter/core/steady_camera_coarse_filter.py
> +        poc_scale_factor = float(self.poc_maximum_image_dimension) / max(self.video_frames_batch.video_reader.resolution)
done

2024-06-21 04:37 UTC, morzh commented on filters/steady_camera_filter/core/steady_camera_coarse_filter.py
> +        self.poc_resolution = int(poc_resolution[0]), int(poc_resolution[1])
done

2024-06-21 04:40 UTC, morzh commented on filters/steady_camera_filter/core/steady_camera_coarse_filter.py
> +        segments_bins = np.linspace(0, (number_bins - 1) * number_frames_to_average, number_bins, dtype=np.int32).reshape(-1, 1) + base_segment_range
Лично моё предпочтение. "На практике" это заставляют так делать на работе. Сишный код иногда вообще не читаем (лично для меня). А экраны давно уже широкоформатные у всех, а пишем всё в столбик.

2024-06-21 04:43 UTC, morzh commented on filters/steady_camera_filter/extract_video_segmens.py
> +        case _:
https://docs-python.ru/tutorial/tsikly-upravlenie-vetvleniem-python/konstruktsija-match-case/

если точное совпадение не подтверждено, то в качестве совпадающего случая будет использоваться последний `case` c подстановочным знаком `_`, если он указан. Если точное совпадение не подтверждено и `case _:` - не существует, то весь блок `match` не выполняется.

2024-06-21 05:05 UTC, morzh commented on filters/steady_camera_filter/extract_video_segmens.py
> +    camera_filter = SteadyCameraCoarseFilter(video_filepath,
done

2024-06-21 11:54 UTC, morzh commented on filters/steady_camera_filter/core/image_registration/image_registration_poc.py
> +ndimageNxMx3 = Annotated[NDArray[np.uint8], Literal["N", "M", 3]]
done

2024-06-21 12:32 UTC, morzh commented on cv_utils/video_reader.py
> +            self._progress.update()
done

2024-06-21 12:33 UTC, morzh commented on cv_utils/video_segments_writer.py
> +        segments = video_segments.segments.flatten()
Я бы оставил пока, это вообще для отладки. Чтобы посмотреть, на каких отрезках видео фильтр считает, что камера не статична.

2024-06-21 12:36 UTC, morzh commented on cv_utils/video_segments_writer.py
> +        filename_frames_range = '_' + str(segment[0]) + '-' + str(segment[1]) + '__'
использую плюшки `numpy` для обработки  `segments`. Пока сделал так, для большей читаемости

2024-06-21 12:37 UTC, morzh commented on cv_utils/video_segments_writer.py
> +        filename_frames_range = '_' + str(segment[0]) + '-' + str(segment[1]) + '__'
```python
start_frame = str(segment[0])
end_frame = str(segment[1])
filename_frames_range = '_' + start_frame + '-' + end_frame + '__'
```

2024-06-21 16:49 UTC, Ma4eteS approved these changes

2024-06-21 16:49 UTC, Ma4eteS commented on cv_utils/video_segments_writer.py
> +        filename_frames_range = '_' + str(segment[0]) + '-' + str(segment[1]) + '__'
flake против создания строк через "+"
Более распространённый и производительный вариант (и по мне самый читаемый):

video_filename = f"{video_filename_base}__{frames_range_prefix}_{start_frame}-{end_frame}.mp4"

2024-06-21 16:49 UTC, Ma4eteS commented on filters/steady_camera_filter/core/steady_camera_coarse_filter.py
> +        segments_bins = np.linspace(0, (number_bins - 1) * number_frames_to_average, number_bins, dtype=np.int32).reshape(-1, 1) + base_segment_range
Согласен. Меня напрягает читать в столбик то что состаляет одну сущность

2024-06-21 16:49 UTC, Ma4eteS commented on cv_utils/video_segments_writer.py
> +            Video segments inversion. Method calculates minus in sense of set theory  :math:`[0, N_{frames} - 1]  \ \backslash  \ segments`.
Понял, UI github не рендерит то что должно быть в итоге...

2024-06-21 17:55 UTC, morzh commented on cv_utils/video_frames_batch.py
> +            batch[index] = frame
Тут бы поподробнее. О каких потоках идёт речь?

2024-06-21 17:57 UTC, morzh commented on cv_utils/video_frames_batch.py
> +        yield batch[:last_batch_frames_number]
Тут просто надо  поять, если мы хапаем по `N` кдаров, то сколько отсанется в итоге. Сам код подправил, вместо

2024-06-21 18:07 UTC, morzh commented on cv_utils/video_segments_writer.py
> +        video_segments_gaps = copy.copy(video_segments)
Набор данных использует `VideoSegmentsWriter` для записи видео. Данная функция сделана только для проверки фильтра статичной камеры. Пожтому думаю не стоит включать `video_segments_gaps` в класс `VideoSegments`.

2024-06-21 18:11 UTC, morzh commented on filters/steady_camera_filter/core/image_registration/image_registration_poc.py
> +        :param image_reference:  reference image
разве мы не должны писать описание к каждому классу, методу и параметру, даже если и так понятно, что он/они делает/ют?

2024-06-21 18:11 UTC, morzh commented on filters/steady_camera_filter/core/steady_camera_coarse_filter.py
> +    def unite_overlapping_ranges(segments: segments_list) -> segments_list:
вообще сделал `np.ndarray`

2024-06-21 18:14 UTC, morzh commented on filters/steady_camera_filter/core/image_registration/image_registration_poc.py
> +        :param new_image: image to add to deque
Изменил всё на `cv2.typing.MatLike` Что думаешь, мне кажется понятно/

2024-06-21 18:15 UTC, morzh commented on filters/steady_camera_filter/core/ocr/craft.py
> +    def draw_polygons(image_shape: tuple[int, int], polygons: list[list[list[int]]]) -> np.ndarray:
исправил

2024-06-21 18:16 UTC, morzh commented on cv_utils/video_segments_writer.py
> +import copy
сделал

2024-06-21 18:18 UTC, morzh commented on filters/steady_camera_filter/core/ocr/easy_ocr.py
> +    def pixel_mask(self, image: cv2.typing.MatLike, output_resolution: tuple[int, int]) -> cv2.typing.MatLike:
есть

2024-06-22 05:35 UTC, morzh commented on cv_utils/video_segments_writer.py
> +            if index_frame == current_segment[0]:
Исправил так,  наверное стало лучше:

2024-06-22 05:37 UTC, morzh commented on filters/steady_camera_filter/core/steady_camera_coarse_filter.py
> +        segments_bins = np.linspace(0, (number_bins - 1) * number_frames_to_average, number_bins, dtype=np.int32).reshape(-1, 1) + base_segment_range
Исправить это легко, вот у мкея всегда вопрос, насколько это добавит читаемости

2024-06-22 10:34 UTC, Ma4eteS commented on cv_utils/video_frames_batch.py
> +            batch[index] = frame
Переменная "batch" это ссылка на массив. 
Когда ты возвращаешь yield batch, ты копию ссылки на этот массив.
Там куда ты отдал ссылку на этот массив, он может быть изменён. 
И если изменение в другом месте будет происходить одновременно с выполнением итерации обновления данных в этом массиве 
batch[index] = frame
конечный массив batch, ссылку на который ты возвращаешь со следующей стерацией yield batch, будет содержать данные, частично или полностью изменённые в разных местах кода.
Чтобы гарантировать потокобезопасность, каждая итерация заполнения массива должна содержать новую инициализацию
batch = np.zeros((self.batch_size, self.video_reader.height, self.video_reader.width, 3))

Ешё один момент по произодительности - zeros, это массив **заполненный** нулями. Чтобы массив стал заполнен нулями, эти значения надо присвоить. Если тебе изначально нужен именно каркас под данные в который будешь записывать значения потом, более выгодно создавать массив через empty
batch = np.empty((self.batch_size, self.video_reader.height, self.video_reader.width, 3))
Для empty numpy выделяет область памяти, но не изменяет содержимое. По этому изначально в таком массиве случайные числа, которые были в памяти на момент её выделения.

2024-06-22 10:34 UTC, Ma4eteS commented on cv_utils/video_frames_batch.py
> +            batch[index] = frame
Переменная "batch" это ссылка на массив. 
Когда ты возвращаешь yield batch, ты копию ссылки на этот массив.
Там куда ты отдал ссылку на этот массив, он может быть изменён. 
И если изменение в другом месте будет происходить одновременно с выполнением итерации обновления данных в этом массиве 
batch[index] = frame
конечный массив batch, ссылку на который ты возвращаешь со следующей стерацией yield batch, будет содержать данные, частично или полностью изменённые в разных местах кода.
Чтобы гарантировать потокобезопасность, каждая итерация заполнения массива должна содержать новую инициализацию
batch = np.zeros((self.batch_size, self.video_reader.height, self.video_reader.width, 3))

Ешё один момент по произодительности - zeros, это массив **заполненный** нулями. Чтобы массив стал заполнен нулями, эти значения надо присвоить. Если тебе изначально нужен именно каркас под данные в который будешь записывать значения потом, более выгодно создавать массив через empty
batch = np.empty((self.batch_size, self.video_reader.height, self.video_reader.width, 3))
Для empty numpy выделяет область памяти, но не изменяет содержимое. По этому изначально в таком массиве случайные числа, которые были в памяти на момент её выделения.

2024-06-22 10:39 UTC, Ma4eteS commented on cv_utils/video_frames_batch.py
> +        yield batch[:last_batch_frames_number]
не понимаю заминку с  "сколько останется кадров в последней стопке".
Ты в цикле накапливаешь индексы,  
index += 1
когда кадры заканчиваются, в index число, которое соответствует количеству кадров обработанных для последнего батча до того как кадры кончились.
Соответственно return batch[:index] вернёт кусок массива с новой пачкой кадров. А 
if index: 
нужен чтобы не получить ошибку если последний батч будет заполнен ровно в размер и на момент когда кадры кончатся, в  index будет 0

2024-06-24 10:35 UTC, merged